language: node_js
node_js:
  - lts/dubnium
cache:
  npm: true
  directories:
    - node_modules
    - themes/tranquilpeak/node_modules
before_install:
  - ci/setup-github-ssh.sh
install:
  - npm install
script:
  - npm run build-prod-firebase
  - npm run build-prod-github
deploy:
  - provider: script
    script: npm run ci-deploy-firebase
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: npm run ci-deploy-github
    skip_cleanup: true
    on:
      branch: master
notifications:
  email:
    on_failure: always
