sudo: required
language: ruby

services:
  - docker

addons:
  ssh_known_hosts: $DEPLOY_HOST


install:
- docker pull yogendra/hugo:latest

script:
- source .env
- site-build-docker

before_deploy:
- openssl aes-256-cbc -K $encrypted_25678052b481_key -iv $encrypted_25678052b481_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: site-deploy $DEPLOY_USER $DEPLOY_HOST $DEPLOY_PATH $DEPLOY_PORT
  on:
    branch: master

notifications:
  email:
    on_failure: always

