dist: trusty
sudo: false

language: java
jdk:
  - oraclejdk8

node_js:
  - "8"

addons:
  apt:
    packages:
    - oracle-java8-installer
    - nodejs
    - graphviz
  ssh_known_hosts:
  - $DEPLOY_HOST

cache:
  yarn: true
  directories:
  - .deploy_git

install: yarn install

script: yarn build

before_deploy:
- openssl aes-256-cbc -K $encrypted_25678052b481_key -iv $encrypted_25678052b481_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- ssh-keyscan -p $DEPLOY_PORT $DEPLOY_HOST >> ~/.ssh/known_hosts
- git config --global user.name "Yogendra Rampuria (TravisCI)"
- git config --global user.email "ci@yogendra.me"
- [[ -d .deploy_git ]] && ( cd .deploy_git; git fetch --unshallow )




deploy:
  provider: script
  skip_cleanup: true
  script:
  - yarn deploy
  on:
    branch: master

notifications:
  email:
    on_failure: always

