sudo: required
language: node_js
node_js:
  - "7"

cache:
  yarn: true
  directories:
  - .deploy_git

install: yarn install

script: yarn build

before_deploy:
- openssl aes-256-cbc -K $encrypted_25678052b481_key -iv $encrypted_25678052b481_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- ssh-keyscan -p $DEPLOY_PORT $DEPLOY_HOST >> ~/.ssh/known_hosts


deploy:
  provider: script
  skip_cleanup: true
  script:
  - hexo hexo --config _config.yml,_config.hosting.yml deploy --host=$DEPLOY_HOST --user=$DEPLOY_USER --root=$DEPLOY_PATH --port=$DEPLOY_PORT
  - hexo hexo --config _config.yml,_config.github.yml deploy
  on:
    branch: master

notifications:
  email:
    on_failure: always

