language: node_js
node_js:
  - lts/dubnium
cache:
  npm: true
  directories:
    - node_modules
    - themes/tranquilpeak/node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_df2bd5da7d4c_key -iv $encrypted_df2bd5da7d4c_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - cp deploy_rsa ~/.ssh/deploy_rsa
  - chmod 400 ~/.ssh/deploy_rsa
  - echo -e "Host github.com\n\tHostName github.com\n\tUser git\n\tIdentityFile ~/.ssh/deploy_rsa\n"
    >> ~/.ssh/config
install:
  - npm install
script:
  - npm run build-prod-firebase
  - npm run build-prod-github
deploy:
  - provider: script
    script: npm run ci-deploy-firebase
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: npm run ci-deploy-github
    skip_cleanup: true
    on:
      branch: master
notifications:
  email:
    on_failure: always
