language: node_js
node_js:
- lts/*
cache:
  npm: true
  directories:
  - node_modules
  - themes/tranquilpeak/node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_df2bd5da7d4c_key -iv $encrypted_df2bd5da7d4c_iv -in deploy_rsa.enc -out deploy_rsa -d
- cp deploy_rsa ~/.ssh/deploy_rsa
- chmod 400 ~/.ssh/deploy_rsa
- echo -e "Host github.com\n\tHostName github.com\n\tUser git\n\tIdentityFile ~/.ssh/deploy_rsa\n" >> ~/.ssh/config
install:
- npm install
script:
- npm run build-prod-firebase
- npm run build-prod-github
deploy:
- provider: script
  script: npm run ci-deploy-firebase
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: npm run ci-deploy-github
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    on_failure: always

env:
  global:
  - secure: "PBJhLXAGxlnJTQrPRSdEp+PTO2lDvCs3L7n07o0XnmaTOFrf7KleGw3wgGr/rMkZfmbuCMBpiwUe+VOcgwGefxHbG7xLVxqcIUopaq/uaMcHy/gYhFTuQJJFVFZIpy37Js6sRM8o8nYbOnWElQJt93SotMZFNmE3SNcxF9ijrCj+RWLd7g3rM31sl3fGGUYg0O/yLS/wvL+aYXeWGhase18c2wdV34MlXmoLE0C/+AiMTCpOqWMNLoBoDYLdETKeisY7CyKi8mEPhBOCMLkcUjW3FMIXJiCBzFk6WD4BTN8ybaMf2HzZc91G8QQs9CT0PExFXUY0tm4w2EOeL7VTtGDclIDawfzp/J0brVPhFwMNSXB1LX7z5zl4IEN3SzyUvCYlUn+7Dto2EsoOsE2n0wrdiIT06l1MdK/4umXdC7hCtcURN57ceni/dz4UZhiNPD+EPizdHeudin+rAjOfNGIKj0wlUwiMp7KhkJtSFFJtTqCv14TtACU8IV2FJ+XQYOYjk9nlP7xrleHmouLxfPR7cShYN7A2ku8aM18yteoxhLDEhKmm6FB6fjDTZzSJWnclejC5pqmkvSR3Ej0J5RMEhFRq+zJccVWwvrNLjr6Hx0bkNBeA+9N/sROJLhV7seNVIWWjc/OREdmt8Jz1BRkqczzqtQ2AJT9owN0fYoM="
