baseURL = "http://example.com/"
languageCode = "en-us"
title = "this = &yogi;"
theme = "minimal"
ignoreFiles = ["^\\.gitkeep$"]

[params]
    author = "Yogendra Rampuria (Yogi)"
    description = "Place to put my thoughts"
    githubUsername = "yogendra"
    accent = "blue"
    showBorder = true
    backgroundColor = "white"
    font = "Quicksand" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
#   highlightLanguages = [ "asciidoc", "apache", "bash", "c", "c++", "coffee", "css", "dockerfile", "go", "html", "http", "java", "javascript", "json", "kotlin", "less", "makefile", "markdown", "nginx", "perl", "php",  "python", "ruby", "scala", "scss", "shell-session", "sql",  "swift", "yaml",  "xml"]
    highlightLanguages = [ "bash" ]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

# [[menu.main]]
#     url = "/project/"
#     name = "Projects"
#     weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/yogendra/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/yogendra/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/yogendrarampuria/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/users/559158/yogi/"
    name = "stack-overflow"
    weight = 5
